version: "3"  # optional since v1.27.0
services:
  web:
    image: nginx:latest
    container_name: "eliteauto_web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend-vue/dist:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # - ./data/img/:/var/www/html/img/:rw
  db:
    image: postgres:latest
    container_name: "eliteauto_db"
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=eliteauto
  backend:
    image: node:14
    container_name: "eliteauto_backend"
    working_dir: /usr/src/app
      #entrypoint: ["/bin/sh","-c"]
    user: "1000:1000"
    volumes: 
      - ./backend-express:/usr/src/app
    command: /bin/bash -c "npm install && npm run dev"
  dev_frontend:
    image: node:14
    container_name: "eliteauto_dev"
    working_dir: /usr/src/app
    volumes:
      - ./frontend-vue:/usr/src/app
    command: /bin/bash -c "npm install && npm run serve -- --port 80 --public http://localhost/dev/"
    user: "1000:1000"
